name: Build
on:
  push:
    tags:
      - qt_static*

env:
  QT_VER: 5.14.1

jobs:
  build_ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - name: Create Build Environment
      shell: bash
      run: |
        mkdir ${{runner.workspace}}/qt5-static
        sudo apt update
        sudo apt install -y build-essential ^libxcb.* libcups2-dev libglu1-mesa-dev libfontconfig1-dev libfreetype6-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb-render-util0-dev libxkbcommon-dev libxkbcommon-x11-dev libpci-dev libicu-dev

    - name: Download
      shell: bash
      run: |
        git clone https://code.qt.io/qt/qt5.git
        cd qt5
        git checkout v${{env.QT_VER}}
        git submodule update --init --recursive

    - name: Configure
      shell: bash
      run: |
        cd qt5
        ./configure -static -release -optimize-size -strip -qt-xcb -xcb-xlib -cups -kms -qt-zlib -qt-libpng -qt-libjpeg -qt-freetype -opengl desktop -platform linux-g++ -opensource -confirm-license -no-compile-examples -nomake examples -nomake tests -skip qtwebengine -prefix${{runner.workspace}}/qt5-static

    - name: Build
      shell: bash
      run: |
        cd qt5
        make -j$(nproc)

    - name: Install
      shell: bash
      run: |
        cd qt5
        make install

    - uses: actions/upload-artifact@v2
      with:
        name: qt${{env.QT_VER}}-static-${{matrix.os}}
        path: ${{runner.workspace}}/qt5-static
        if-no-files-found: error
